apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-prometheus
subjects:
- kind: Group 
  namespace: prometheus  
  name: system:serviceaccounts:prometheus
roleRef:
  kind: ClusterRole
  name: readpod
  apiGroup: rbac.authorization.k8s.io
