apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-mon
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: nginx-mon
  endpoints:
  - targetPort: 80
