apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mon
  namespace: monitoring  
spec:
  selector:
    matchLabels:
      app: nginx-mon
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-mon
    spec:
      containers:
      - name: nginx-mon
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf  
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:1.0'
        args:
          - '-nginx.scrape-uri=http://localhost/basic_status'
        ports:
          - containerPort: 9113
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx-config
          name: nginx-config      
