apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: otus-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <begunov@mail.ru>
    privateKeySecretRef:
      name: otus-templ
    solvers:
    - http01:
        ingress:
          class: nginx