apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      initContainers:
      - name: wait-frontend
        image: alpine:3.18
        command: ['sh', '-c', 'set -x; apk add --no-cache curl && sleep 5 && curl "http://${FRONTEND_ADDR}" && echo "OK";']
#        command: ['sh', '-c', 'set -x;  apk add --no-cache curl && 
#          until timeout -t 2 curl -f "http://${FRONTEND_ADDR}"; do 
#            echo "waiting for http://${FRONTEND_ADDR}"; 
#            sleep 2;
#          done;']
        env:
        - name: FRONTEND_ADDR
          #value: "{{ .Values.ingress.host }}:80"
          value: "158.160.147.110:80"
      containers:
      - name: main
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: FRONTEND_ADDR
          #value: "{{ .Values.ingress.host }}:80"
          value: "158.160.147.110:80"
        - name: USERS
          value: "10"
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
