config:
  outputs: |
    [OUTPUT]
        Name  es
        Match *
        Host  elasticsearch
        Port  9200
        Suppress_Type_Name On
        Replace_Dots    On
   
nodeSelector:
  yandex.cloud/node-group-id: cat4p366c8813vq464j2
tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

