apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: cleverok2/frontend_demo:0.1
    name: frontend
    resources: {}
    env:
    - name: PORT
      value: "28000" 
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "productcatalog:28001"
    - name: CURRENCY_SERVICE_ADDR
      value: "currencyservice:28002"
    - name: CART_SERVICE_ADDR
      value: "cartservice:28003"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "recommendationservice:28004"
    - name: CHECKOUT_SERVICE_ADDR
      value: "checkoutservice:28005" 
    - name: SHIPPING_SERVICE_ADDR
      value: "shippingservice:28006"
    - name: AD_SERVICE_ADDR
      value: "adservice:28007"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
